### ISSUE TITLE
ridgeback_dual_arm gazebo+moveit

### ISSUE THREAD

**Issue by TouchDeeper** [ridgeback/ridgeback_manipulation#1]
Hi,your company‘s robot is outstanding. Our project team buy a reidgeback, and i'm building the  dual_ur_ridgeback gazebo+moveit project. Thanks for your project *ridgeback_manipulation*, the project teach me how to start. I achieve dual_ur gazebo+moveit as the video show. However when i add the dual_ur to the ridgeback, the ridgeback can't work normally in gazebo,and i'm stuck here. Do you have the plan to add the dual_ur to ridgeback in gazebo+moveit? Thanks a lot!
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39310744/49794299-36a9d900-fd72-11e8-8b41-69030f291467.gif)

**Comment by dniewinski** [comment]
Hi @TouchDeeper .  Looking at your video, it looks like everything is working properly with MoveIt! and Gazebo.  What kinds of issues are you having?

**Comment by TouchDeeper** [comment]
Hi,@dniewinski,the arm work properly, but the ridgeback can't move with your package.

**Comment by dniewinski** [comment]
@TouchDeeper I believe the issue might be related to a bug in gazebo_ros_control (https://github.com/ros-simulation/gazebo_ros_pkgs/issues/612).  A quick test of this would be to grab the Ridgeback and lift up into the air and drop it.  If it falls down, but looks like the arms are acting like parachutes, than this is the issue.  This issue doesn't let the Ridgeback properly grip the ground, which means it can't drive.

I haven't been able to fix it yet, which is why there isn't a gazebo package for ridgeback_manipulation.  Try to follow along with the suggestions in that link and let me know if you are able to get something usable out of it.

**Comment by TouchDeeper** [comment]
Hi,@dniewinski ,thanks for your reply. Take a sigh of relief，I fixed it just now.

The same as you ,the first time i get the issue about falling down seems like a parachutes is when a wheel of the car can't land in the gazebo. there is a link about how to solve this issue [https://github.com/mintar/mimic_joint_gazebo_tutorial](url). 

Just as the tutorial said, i change the position_controllers to effort_controllers, the gravity problem disappear,but,so sad,the arm vibration in gazebo is too large, even cause the model  rush.Then i find a project about youbot [https://github.com/mas-group/youbot_simulation](url), referring to this project, i solve the problem of model rush. Hope it helps you.

**Comment by dniewinski** [comment]
@TouchDeeper If your issue is resolved, please close this issue.  I will try to implement a proper gazebo package for this in the future

**Comment by TouchDeeper** [comment]
Hi，@dniewinski,i will colse this issue. I'm looking forward to your update.
